server:
  port: 8081

spring:
  application:
    name: proxy

  # Configuración para el REDIS de la CÁTEDRA
  data:
    redis:
      host: 192.168.194.250
      port: 6379
      # Si se requiere contraseña, se añade aquí:
      # password: "example_password"

  # Configuración para el KAFKA de la CÁTEDRA
  kafka:
    bootstrap-servers: 192.168.194.250:9092
    consumer:
      group-id: "AugustoGiuffrida"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer