server:
  port: 8081

spring:
  application:
    name: proxy

  # Configuración para REDIS
  data:
    redis:
      host: 192.168.194.250
      port: 6379
      # password: "example_password"

  # Configuración para KAFKA
  kafka:
    bootstrap-servers: 192.168.194.250:9092
    consumer:
      group-id: "AugustoGiuffrida"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

application:
  backend-url: "http://localhost:8080"
  catedra-api-url: "http://192.168.194.250:8080"
  bloquear-asientos-url: "/api/endpoints/v1/bloquear-asientos"
  realizar-venta-url: "/api/endpoints/v1/realizar-venta"